<?php include 'component/billboard.php' ?>
<?php include 'component/features.php' ?>
<?php include 'component/categories.php' ?>
<?php include 'component/newarrival.php' ?>
<?php include 'component/collection.php' ?>
<?php include 'component/bestseller.php' ?>
<?php include 'component/videooverflow.php' ?>
<?php include 'component/testimonials.php' ?>
<?php include 'component/newarrival.php' ?>
<?php include 'component/blog.php' ?>
<?php include 'component/partnership.php' ?>
<?php include 'component/newsletter.php' ?>
<?php include 'component/socialmedia.php' ?>